# Generated by Django 3.1.5 on 2021-01-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='marketcapsize',
            name='market_cap_size',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
