# Generated by Django 3.1.5 on 2021-01-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210110_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='company_name_ticker',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
